import {
    LayoutDashboard,
    Users,
    FileText,
    Shield,
    CreditCard,
    FileBarChart,
    UserCircle,
    LogOut,
    Hash,
    Server,
    ScrollText,
    Activity,
    Wrench,
    FileSearch,
    BookOpen,
    Clock,
    Cog,
    AlertTriangle,
    Bell,
    UserCog,
    Building2,
    BarChart3,
    Database,
    Settings2,
    Plus,
    DollarSign,
    MessageSquare,
    Car,
} from 'lucide-react';

export type NavItem = {
    title: string;
    href?: string;
    icon: any;
    roles?: string[];
    excludeRoles?: string[];
    translationKey?: string;
    items?: NavItem[]; // Nested items for collapsible menus
    order?: number; // Sıralama için
};

export const navigationConfig: NavItem[] = [
    // SuperAdmin Özel Menüler (önce SuperAdmin, çünkü SuperAdmin Admin menülerini de görebilir)
    {
        title: 'Super Admin Dashboard',
        href: '/superadmin/dashboard',
        icon: Shield,
        roles: ['SuperAdmin'],
        translationKey: 'superAdminDashboard',
        order: 1,
    },

    {
        title: 'Dealer Management',
        icon: Building2,
        roles: ['SuperAdmin'],
        translationKey: 'dealerManagement',
        order: 2,
        items: [
            {
                title: 'All Dealers',
                href: '/admin/dealers',
                icon: Building2,
                roles: ['SuperAdmin'],
                translationKey: 'allDealers',
                order: 1,
            },
            {
                title: 'Dealer Performance',
                href: '/superadmin/dealers/performance',
                icon: BarChart3,
                roles: ['SuperAdmin'],
                translationKey: 'dealerPerformance',
                order: 2,
            },
        ],
    },

    {
        title: 'Reports & Analytics',
        href: '/admin/reports',
        icon: BarChart3,
        roles: ['SuperAdmin'],
        translationKey: 'reportsAnalytics',
        order: 7,
    },

    // Admin & SuperAdmin (Ortak menüler)
    {
        title: 'Dashboard',
        href: '/admin/dashboard',
        icon: LayoutDashboard,
        roles: ['Admin'],
        excludeRoles: ['SuperAdmin'],
        translationKey: 'dashboard',
        order: 1,
    },
    {
        title: 'Dealers',
        href: '/admin/dealers',
        icon: Users,
        roles: ['Admin'],
        translationKey: 'dealers',
        order: 2,
    },
    {
        title: 'Customers',
        href: '/admin/customers',
        icon: Users,
        roles: ['Admin', 'SuperAdmin'],
        translationKey: 'customers',
        order: 2.5,
    },
    {
        title: 'Vehicles',
        href: '/admin/vehicles',
        icon: Car,
        roles: ['Admin', 'SuperAdmin'],
        translationKey: 'vehicles',
        order: 2.6,
    },
    {
        title: 'Observers',
        icon: UserCog,
        roles: ['Admin', 'SuperAdmin'],
        translationKey: 'observers',
        order: 3,
        items: [
            {
                title: 'Observer Management',
                href: '/admin/observers',
                icon: UserCog,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'observerManagement',
                order: 1,
            },
            {
                title: 'Task Management',
                href: '/admin/observers/tasks',
                icon: ScrollText,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'taskManagement',
                order: 2,
            },
        ],
    },
    {
        title: 'Policies',
        icon: FileText,
        roles: ['Admin', 'SuperAdmin'],
        translationKey: 'policiesMenu',
        order: 4,
        items: [
            {
                title: 'Policy Series',
                href: '/admin/policy-series',
                icon: Hash,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'policySeries',
                order: 1,
            },
            {
                title: 'Policy Types',
                href: '/admin/config/policy-types',
                icon: FileText,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'policyTypes',
                order: 2,
            },
            {
                title: 'Price Lists',
                href: '/admin/config/price-lists',
                icon: DollarSign,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'priceLists',
                order: 3,
            },
            {
                title: 'Policies',
                href: '/admin/policies',
                icon: FileText,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'policies',
                order: 4,
            },
        ],
    },
    {
        title: 'Reports',
        href: '/admin/reports',
        icon: FileBarChart,
        roles: ['Admin'],
        translationKey: 'reports',
        order: 5,
    },
    {
        title: 'Notifications',
        href: '/admin/notifications',
        icon: Bell,
        roles: ['Admin', 'SuperAdmin', 'Dealer', 'Observer', 'Customer'],
        translationKey: 'notifications',
        order: 6,
    },
    {
        title: 'System Management',
        icon: Server,
        roles: ['Admin', 'SuperAdmin'],
        translationKey: 'systemManagement',
        order: 7,
        items: [
            {
                title: 'Settings',
                href: '/admin/config/settings',
                icon: Cog,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'settings',
                order: 1,
            },
            {
                title: 'Log Records',
                href: '/admin/system/logs',
                icon: ScrollText,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'logRecords',
                order: 2,
            },
            {
                title: 'System Usage',
                href: '/admin/system/usage',
                icon: Activity,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'systemUsage',
                order: 3,
            },
            {
                title: 'Maintenance Mode',
                href: '/admin/system/maintenance',
                icon: Wrench,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'maintenanceMode',
                order: 4,
            },
            {
                title: 'Audit Logs',
                href: '/admin/system/audit',
                icon: FileSearch,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'auditLogs',
                order: 5,
            },
            {
                title: 'Scheduled Tasks',
                href: '/admin/config/scheduled-tasks',
                icon: Clock,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'scheduledTasks',
                order: 6,
            },
        ],
    },
    {
        title: 'User Management',
        icon: Users,
        roles: ['Admin', 'SuperAdmin'],
        translationKey: 'userManagement',
        order: 8,
        items: [
            {
                title: 'Users',
                href: '/admin/config/users',
                icon: Users,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'users',
                order: 1,
            },
            {
                title: 'Roles',
                href: '/admin/config/roles',
                icon: Shield,
                roles: ['Admin', 'SuperAdmin'],
                translationKey: 'roles',
                order: 2,
            },
        ],
    },

    // Dealer
    {
        title: 'Dashboard',
        href: '/dealer/dashboard',
        icon: LayoutDashboard,
        roles: ['Dealer'],
        translationKey: 'dashboard',
        order: 1,
    },
    {
        title: 'Customers',
        href: '/dealer/customers',
        icon: Users,
        roles: ['Dealer'],
        translationKey: 'customers',
        order: 2,
    },
    {
        title: 'Vehicles',
        href: '/dealer/vehicles',
        icon: Car,
        roles: ['Dealer'],
        translationKey: 'vehicles',
        order: 2.5,
    },
    {
        title: 'Policies',
        icon: FileText,
        roles: ['Dealer'],
        translationKey: 'policiesMenu',
        order: 3,
        items: [
            {
                title: 'All Policies',
                href: '/dealer/policies',
                icon: FileText,
                roles: ['Dealer'],
                translationKey: 'policies',
                order: 1,
            },
            {
                title: 'Create Policy',
                href: '/dealer/policies/new',
                icon: Plus,
                roles: ['Dealer'],
                translationKey: 'createPolicy',
                order: 2,
            },
        ],
    },
    {
        title: 'Financial',
        href: '/dealer/financial',
        icon: DollarSign,
        roles: ['Dealer'],
        translationKey: 'financial',
        order: 4,
    },
    {
        title: 'Payments',
        href: '/dealer/payments',
        icon: CreditCard,
        roles: ['Dealer'],
        translationKey: 'payments',
        order: 5,
    },
    {
        title: 'Reports',
        href: '/dealer/reports',
        icon: FileBarChart,
        roles: ['Dealer'],
        translationKey: 'reports',
        order: 6,
    },
    // Notifications removed from sidebar - available in header dropdown
    {
        title: 'Profile',
        href: '/dealer/profile',
        icon: UserCircle,
        roles: ['Dealer'],
        translationKey: 'profile',
        order: 7,
    },
    {
        title: 'Settings',
        href: '/dealer/settings',
        icon: Settings2,
        roles: ['Dealer'],
        translationKey: 'settings',
        order: 8,
    },

    // Customer
    {
        title: 'My Policies',
        href: '/customer/policies',
        icon: FileText,
        roles: ['Customer'],
        translationKey: 'policies',
        order: 1,
    },
    {
        title: 'Claims',
        icon: AlertTriangle,
        roles: ['Customer'],
        translationKey: 'claims',
        order: 2,
        items: [
            {
                title: 'My Claims',
                href: '/customer/claims',
                icon: FileText,
                roles: ['Customer'],
                translationKey: 'myClaims',
                order: 1,
            },
            {
                title: 'Report Claim',
                href: '/customer/claims/new',
                icon: Plus,
                roles: ['Customer'],
                translationKey: 'reportClaim',
                order: 2,
            },
        ],
    },
    {
        title: 'Support',
        icon: Bell,
        roles: ['Customer'],
        translationKey: 'support',
        order: 3,
        items: [
            {
                title: 'Contact Support',
                href: '/customer/support',
                icon: MessageSquare,
                roles: ['Customer'],
                translationKey: 'contactSupport',
                order: 1,
            },
            {
                title: 'My Tickets',
                href: '/customer/support/tickets',
                icon: FileText,
                roles: ['Customer'],
                translationKey: 'myTickets',
                order: 2,
            },
            {
                title: 'FAQ',
                href: '/customer/support/faq',
                icon: BookOpen,
                roles: ['Customer'],
                translationKey: 'faq',
                order: 3,
            },
        ],
    },
    {
        title: 'Profile',
        href: '/customer/profile',
        icon: UserCircle,
        roles: ['Customer'],
        translationKey: 'profile',
        order: 4,
    },
    {
        title: 'Reports',
        href: '/customer/reports',
        icon: FileBarChart,
        roles: ['Customer'],
        translationKey: 'reports',
        order: 5,
    },
    {
        title: 'Settings',
        href: '/customer/settings',
        icon: Settings2,
        roles: ['Customer'],
        translationKey: 'settings',
        order: 6,
    },

    // Observer
    {
        title: 'Dashboard',
        href: '/observer/dashboard',
        icon: LayoutDashboard,
        roles: ['Observer'],
        translationKey: 'dashboard',
        order: 1,
    },
    {
        title: 'Dealers',
        href: '/observer/dealers',
        icon: Users,
        roles: ['Observer'],
        translationKey: 'dealers',
        order: 2,
    },
    {
        title: 'Tasks',
        href: '/observer/tasks',
        icon: Clock,
        roles: ['Observer'],
        translationKey: 'tasks',
        order: 3,
    },
    {
        title: 'Activity Logs',
        href: '/observer/activity-logs',
        icon: Activity,
        roles: ['Observer'],
        translationKey: 'activityLogs',
        order: 4,
    },
    {
        title: 'System Status',
        href: '/observer/system-status',
        icon: Server,
        roles: ['Observer'],
        translationKey: 'systemStatus',
        order: 5,
    },
    {
        title: 'Reports',
        href: '/observer/reports',
        icon: FileBarChart,
        roles: ['Observer'],
        translationKey: 'reports',
        order: 6,
    },
];
